---
# tasks file for base
- name: activate epel
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/oracle-epel-ol7.repo
    regexp: '^enabled=0'
    line: enabled=1

- name: Install clamav
  package:
    name: clamav
    state: latest # noqa package-latest
  register: clamav_packages_install

- name: Install chrony
  package:
    name: chrony
    state: latest # noqa package-latest

- name: Activate cron job to run Ansible
  ansible.builtin.cron:
    name: Schedule for Ansible
    minute: "*/15"
    job: "/usr/bin/ansible-playbook -i localhost, /opt/oci-rsa/{{ ansible_playbook_name }}/main.yml --connection=local"

- name: Ensure chrony.conf has correct server
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^server'
    line: 'server 169.254.169.254 iburst'
  notify: 
    - Restart chronyd

- name: Install suricata
  package:
    name: suricata
    state: present # noqa package-latest

- name: Update suricata rules
  ansible.builtin.command: /bin/suricata-update
  args:
    creates: /var/lib/suricata/rules/suricata.rules

- name: deploy suricata sysconfig
  ansible.builtin.template:
    src: suricata.sysconfig.j2
    dest: /etc/sysconfig/suricata
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Restart suricata

- name: schedule suricata update
  ansible.builtin.cron:
    name: Schedule for suricata
    minute: "13"
    hour: "1"
    job: "/bin/suricata-update"

- name: scanning deployment 
  meta: noop

- name: Install lynis
  package:
    name: lynis
    state: latest # noqa package-latest

- name: Install nmap
  package:
    name: nmap
    state: latest # noqa package-latest

- name: Install git
  package:
    name: git
    state: latest # noqa package-latest

- name: Install scipag (from Github)
  ansible.builtin.git:
    repo: 'https://github.com/scipag/vulscan'
    dest: '/opt/scipag_vulscan'

- name: schedule nmap scanner
  ansible.builtin.cron:
    name: Schedule for nmap scanner
    user: nobody
    minute: "23"
    hour: "3"
    job: '/usr/bin/nmap -Pn -sV --script=/opt/scipag_vulscan/vulscan.nse localhost | logger -t nmap_scipag_vulscan'

- name: schedule lynis pentest
  ansible.builtin.cron:
    name: Schedule for lynis pentest
    user: root
    minute: "23"
    hour: "2"
    job: '/bin/lynis audit system --pentest'

- name: Add the wazuh group
  ansible.builtin.group:
    name: wazuh
    state: present

- name: Add the wazuh user
  ansible.builtin.user:
    name: wazuh
    comment: Wazuh User
    group: wazuh

- name: Create bin directory
  ansible.builtin.file:
    path: "{{ oci_rsa_path }}/bin"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: deploy software inventory
  ansible.builtin.template:
    src: software_inventory.sh.j2
    dest: "{{ oci_rsa_path }}/bin/software_inventory.sh"
    owner: root
    group: root
    mode: "u+rwx"
  when: resource_bucket_name is defined

- name: schedule software inventory
  ansible.builtin.cron:
    name: Schedule for software inventory
    hour: "2"
    job: "{{ oci_rsa_path }}/bin/software_inventory.sh"
  when: resource_bucket_name is defined

- name: Deploy freshclam configuration for logging
  ansible.builtin.template:
    src: freshclam.conf.j2
    dest: "/etc/freshclam.conf"
    owner: root
    group: root
    mode: "u+rwx"
  register: freshclam_config_template

- name: Run freshclam after ClamAV packages change.
  command: freshclam
  when: clamav_packages_install.changed
  register: freshclam_result
  failed_when:
    - freshclam_result is failed
    - freshclam_result.stderr.find('locked by another process') != -1

- name: Reload systemd after adding service.
  systemd:
    state: stopped
    daemon_reload: true
    name: "{{ clamav_freshclam_daemon }}"
  when: freshclam_config_template.changed

- name: Ensure ClamAV freshclam daemon is running (if configured).
  service:
    name: "{{ clamav_freshclam_daemon }}"
    state: started
    enabled: true

- name: schedule clamscan
  ansible.builtin.cron:
    name: Schedule for running clamscan
    hour: "2"
    job: "clamscan -r / -i -o --exclude ^/var/lib/suricata/update/cache --exclude ^/usr/bin/pnscan --exclude-dir ^/sys > /var/log/clamscan.errors | logger -t clamd"