---
# tasks file for base
- name: activate epel
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/oracle-epel-ol7.repo
    regexp: '^enabled=0'
    line: enabled=1

- name: Install chrony
  package:
    name: chrony
    state: latest # noqa package-latest

- name: Activate cron job to run Ansible
  ansible.builtin.cron:
    name: Schedule for Ansible
    minute: "*/15"
    job: "/usr/bin/ansible-playbook -i localhost, /opt/oci-rsa/{{ ansible_playbook_name }}/main.yml --connection=local"

- name: Ensure chrony.conf has correct server
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^server'
    line: 'server 169.254.169.254 iburst'
  notify: 
    - Restart chronyd

- name: Install suricata
  package:
    name: suricata
    state: present # noqa package-latest

- name: Update suricata rules
  ansible.builtin.command: /bin/suricata-update
  args:
    creates: /var/lib/suricata/rules/suricata.rules

- name: deploy suricata sysconfig
  ansible.builtin.template:
    src: suricata.sysconfig.j2
    dest: /etc/sysconfig/suricata
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Restart suricata

- name: schedule suricata update
  ansible.builtin.cron:
    name: Schedule for suricata
    minute: "13"
    hour: "1"
    job: "/bin/suricata-update"

- name: scanning deployment 
  meta: noop

- name: Install lynis
  package:
    name: lynis
    state: latest # noqa package-latest

- name: Install nmap
  package:
    name: nmap
    state: latest # noqa package-latest

- name: Install git
  package:
    name: git
    state: latest # noqa package-latest

- name: Install scipag (from Github)
  ansible.builtin.git:
    repo: 'https://github.com/scipag/vulscan'
    dest: '/opt/scipag_vulscan'

- name: schedule nmap scanner
  ansible.builtin.cron:
    name: Schedule for nmap scanner
    user: nobody
    minute: "23"
    hour: "3"
    job: '/usr/bin/nmap -Pn -sV --script=/opt/scipag_vulscan/vulscan.nse localhost | logger -t nmap_scipag_vulscan'

- name: schedule lynis pentest
  ansible.builtin.cron:
    name: Schedule for lynis pentest
    user: root
    minute: "23"
    hour: "2"
    job: '/bin/lynis audit system --pentest'

- name: run software inventory
  shell: rpm -qa --queryformat '%{NAME}, "%{VENDOR}", %{VERSION}, "%{LICENSE}", "%{SUMMARY}"\n' | grep -iv oracle | sort > {{ temp_report_path }}/inventory.txt
  args:
    warn: false
  become: true

- name: put the software inventory result to bucket
  shell: "oci os object put -bn {{ bucket_name }} --name {{ file_name }} --file {{ temp_report_path }}/inventory.txt --force"
  environment:
    OCI_CLI_AUTH: instance_principal
  become: true

- name: remove the inventory report from instance
  file:
    state: absent
    path:  "{{ temp_report_path }}/inventory.txt"
  become: true