---
# handlers file for base
  - name: Restart chronyd
    ansible.builtin.service:
      name: chronyd
      state: restarted
    become: true
  - name: Restart suricata
    ansible.builtin.service:
      name: suricata
      state: restarted
    become: true

  - name: Restart clamav-freshclam daemon
    service:
      name: "{{ clamav_freshclam_daemon }}"
      state: restarted
